include:
  - board: ble_micro_pro
    shield: the_foobar_keyboard_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ble_micro_pro
    shield: the_foobar_keyboard_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y