# 左はセントラル
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# 電池残量の通知
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# ZMK Prospector Scanner
CONFIG_ZMK_STATUS_ADVERTISEMENT=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_ZMK_STATUS_ADV_ACTIVITY_BASED=y
CONFIG_ZMK_STATUS_ADV_ACTIVE_INTERVAL_MS=200
CONFIG_ZMK_STATUS_ADV_IDLE_INTERVAL_MS=10000
CONFIG_ZMK_STATUS_ADV_ACTIVITY_TIMEOUT_MS=120000

CONFIG_PROSPECTOR_MAX_LAYERS=10